Default:
  seed: 0
  hidden: 32
  sparse: False
  lr: 0.001
  weight_decay: 0
  epochs: 300
  dropout: 0.5
  nheads: 2
  alpha: 0.2

cora:
  seed: 0
  hidden: 32
  sparse: False
  lr: 0.005
  weight_decay: 0.001
  epochs: 300
  dropout: 0.5
  nheads: 2
  alpha: 0.2

citeseer:
  seed: 0
  hidden: 32
  sparse: False
  lr: 0.005
  weight_decay: 0.001
  epochs: 300
  dropout: 0.5
  nheads: 2
  alpha: 0.2

pubmed:
  seed: 0
  hidden: 32 #32
  sparse: False
  lr: 0.005
  weight_decay: 0.0005
  epochs: 300
  dropout: 0.5
  nheads: 2
  alpha: 0.2

ogbn-arxiv:
  seed: 0
  hidden: 256
  sparse: True
  lr: 0.01
  weight_decay: 0
  epochs: 500
  dropout: 0.5
  nheads: 2
  alpha: 0.2