Default:
  seed: 0
  hidden: 32
  sparse: False
  lr: 0.001
  weight_decay: 0
  epochs: 300
  dropout: 0.5

cora:
  seed: 0
  hidden: 32
  sparse: False
  lr: 0.005
  weight_decay: 0.001
  epochs: 300
  dropout: 0.5

citeseer:
  seed: 0
  hidden: 32
  sparse: False
  lr: 0.005
  weight_decay: 0.001
  epochs: 300
  dropout: 0.5

pubmed:
  seed: 0
  hidden: 32
  sparse: False
  lr: 0.005
  weight_decay: 0.0005
  epochs: 300
  dropout: 0.5

ogbn-arxiv:
  seed: 0
  hidden: 256
  sparse: True
  lr: 0.01
  weight_decay: 0
  epochs: 500
  dropout: 0.5